### ISSUE TITLE
Icon type lacks constructor.

### ISSUE THREAD

**Issue by brunnerh** [IBM/carbon-icons-svelte#88]
Currently you get type errors when trying to construct a carbon icon programmatically with TypeScript.

E.g.

```js
new Edit20({ target: element });
```

> Expected 0 arguments, but got 1. ts(2554)

`CarbonIcon` should probably extend `SvelteComponentDev`, because that is where the common component constructor signature is defined. Alternatively the constructor definition could be copied over into the icon type.

**Comment by metonym** [comment]
Yeah, it needs to extend from `SvelteComponentTyped`. The types for this library were written before `SvelteComponentTyped` was added

**Comment by metonym** [comment]
Fixed and released in v10.27.0
